{% set name = "robotframework-assertion-engine" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/robotframework_assertion_engine-{{ version }}.tar.gz
  sha256: eaadd3bdab280351745c4234a8c6d63f50972b09906da122e4bb784ca9556ea0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.8.1,<4.0
    - robotframework >=5.0.1
    - robotframework-pythonlibcore >=3.0.0

test:
  imports:
    - assertionengine

about:
  home: https://github.com/MarketSquare/AssertionEngine
  summary: Generic way to create meaningful and easy to use assertions for the Robot Framework libraries.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
