{% set name = "robotframework-assertion-engine" %}
{% set version = "3.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/robotframework_assertion_engine-{{ version }}.tar.gz
  sha256: b78728eb083b12b6545f32b7cface156d36891d4d1d63fb3df2d3667ccd9bdaa

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - python >={{ python_min }},<4.0
    - robotframework >=5.0.1
    - robotframework-pythonlibcore >=3.0.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - assertionengine

about:
  home: https://github.com/MarketSquare/AssertionEngine
  summary: Generic way to create meaningful and easy to use assertions for the Robot Framework libraries.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
